<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Neue hinzufgen</name>
   <tag></tag>
   <elementGuidId>9e0ceb2f-bc7b-424b-8f6d-917bb2690a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Neue hinzufügen')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c5df234-0798-46e5-a53a-9b828b70a624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>014add9a-27c5-45bd-bbcc-e1223d2798cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>664916fa-4d49-45cc-a86e-feabec2524f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>d32ba781-a86b-45d4-be9f-ce2c85b7047e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>c5996437-5ecf-4ddc-91c8-4e6141cbe9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5104a516-8b3d-40a6-80a9-d58a1f3f524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>f9d378c0-c388-44d9-ba82-6d64417b2d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>11bdc98a-b525-4882-8701-9418bd540a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>5a92e4c8-50be-4bef-82ea-52e50dae1534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>20a1411d-0ee1-4c38-84d2-6eccfa47397c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7230b165-39b9-4df5-9b0a-3ee03c12f5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>64c17b65-0bf7-480a-bba8-ae09a8102abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>4766c238-d548-4874-bc61-34b7f4b508eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>e964713b-d883-4649-9448-ff833c148ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>0d04c2b6-24da-4e49-bbf2-cc50d960d69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d8d7840-ebf2-4eaf-b4c4-266c525f28ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>4c28fd23-77b4-475e-a2f9-2284407e40ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>a16ccdd0-bbc6-4240-8466-49678adc894b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>49eae5bc-02e0-4ce2-aa65-fbe4e247b2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>3571d6e4-8f6f-40ba-8530-a4563b2cab3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b1a8714-2d6c-439b-9d8b-c7dfd7752c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>6caf4b12-1543-41e8-87de-79a48bd82710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>20059572-8b7c-4a78-ad81-581e46ae40ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>a9fba8bf-6303-4b63-9f70-af0e88c695d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>b2d1687a-4b02-419c-a7d5-39d677469a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe0ede9a-d13b-4561-9671-392c1b1264d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>5ba2d988-8fac-4fbe-9312-6d7ff14a8140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>b1a24604-75ba-48ab-a812-07803e1ddee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>00759438-8068-42dc-bd65-9844850bd3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>10c3183b-c7cc-4b73-98b2-d37777703184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4e12cee-e85b-4512-b57b-0e75fab55f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>8c974322-d8de-4f30-a287-9eef0d691200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>5c229e8a-86be-4718-9747-6f6dd7a8a40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>5223e30c-45ef-4a0d-a692-ed5715422727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>e2be1eed-3a5c-4a3e-be97-571ef67b81d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>451bfb5d-45fb-4b39-a1a4-56fc4a4f498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>3a125344-76e9-4bde-af8d-558e3edee8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>34aa3e7b-c52c-492d-a872-6319869149fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>74ed5528-541b-461f-b185-1c675e89a11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>f0671759-3c4c-4026-8c81-36a55385a1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46c7e78e-96ab-4187-90b7-9277fc3b51de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>78e40fe6-3024-41f0-8865-cfd12a92199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/consultants/create</value>
      <webElementGuid>8d19e7e4-467a-4c3b-9aff-91c2bc9c3587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>3893bb5b-24d5-42e4-927b-74b02ecba185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[2]/div[@class=&quot;row d-flex align-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>1df26f71-7814-4141-b0e4-78cff29267d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Neue hinzufügen')]</value>
      <webElementGuid>b711027c-8e17-474a-8be5-9260cd4f88e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROCKEN Kontakt'])[3]/following::a[1]</value>
      <webElementGuid>d7979d23-8ea0-45e6-bbbd-2bdcae9d59df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::a[1]</value>
      <webElementGuid>dfd3ba3f-fca5-44d0-b461-ac0ced6764c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avatar'])[1]/preceding::a[1]</value>
      <webElementGuid>360f6811-7841-4593-9b1e-621bf38354c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[1]</value>
      <webElementGuid>bb418ca6-6628-4cca-995f-5dd8f656bd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neue hinzufügen']/parent::*</value>
      <webElementGuid>34da1a41-a2e1-4624-887e-f4ffdcdcebcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/consultants/create')]</value>
      <webElementGuid>753d9f1e-5bce-4791-91d1-00410d68e822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>aa3d9441-412a-404e-b8d9-9fd0a06e91be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/consultants/create' and (text() = 'Neue hinzufügen ' or . = 'Neue hinzufügen ')]</value>
      <webElementGuid>5edd6006-0807-4570-a23e-e070c39a9b48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
