<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Acquired_btn btn-icon btn-default</name>
   <tag></tag>
   <elementGuidId>c42bc113-73c2-4f3a-9399-ad6dbe513a58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mandatesGrid-container']/table/tbody/tr[3]/td[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4016c495-941e-4633-8c7a-af5aaad77aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon btn-default</value>
      <webElementGuid>18d5fca6-51be-4e1c-bb35-29bc372ab1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mandates/update/26</value>
      <webElementGuid>b11487f6-b647-4513-a2c4-0bcc18c00c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[5]/div[1]/a[@class=&quot;btn btn-icon btn-default&quot;]</value>
      <webElementGuid>7c9ec028-9fd1-43b7-a12d-48d4d9aa6be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9e3e9e6-c6e5-4b50-876a-9cdb1d10cfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon btn-default</value>
      <webElementGuid>5167a9bb-3a08-49a1-97ad-5012e42eea40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mandates/update/26</value>
      <webElementGuid>cdb3e275-aef9-423a-83e5-843f2429cac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[5]/div[1]/a[@class=&quot;btn btn-icon btn-default&quot;]</value>
      <webElementGuid>a3720d71-5b37-4896-8ea6-f832e7a014e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd47a2f2-8ead-46e8-9e38-03bac1e01215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon btn-default</value>
      <webElementGuid>7095b37d-8616-4909-8968-9c9b0df65b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mandates/update/26</value>
      <webElementGuid>f1499b19-8bc2-4a9d-bc6c-e9bcc97d0b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[5]/div[1]/a[@class=&quot;btn btn-icon btn-default&quot;]</value>
      <webElementGuid>11eb59cf-7051-410f-bd3d-ec47a195b0f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mandatesGrid-container']/table/tbody/tr[3]/td[5]/div/a</value>
      <webElementGuid>ef7a2190-ef3c-40fd-907c-25203deefa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquired'])[3]/following::a[1]</value>
      <webElementGuid>94e05a52-d8df-4469-aca2-44dfc4ecb31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ivan Godonuk'])[3]/following::a[2]</value>
      <webElementGuid>8b76ca85-b894-4af4-98eb-e45d52e32945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Lab'])[1]/preceding::a[2]</value>
      <webElementGuid>ffee6bdc-2735-444a-8b0d-4d40b2f9970f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancy from executive (m/w/d)'])[1]/preceding::a[3]</value>
      <webElementGuid>4b632db6-4676-4ebb-982f-bf13e8752542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mandates/update/26')]</value>
      <webElementGuid>57d9693f-3940-4cc2-9770-f4c9ee5e9d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/div/a</value>
      <webElementGuid>504d524a-5d61-4634-8d15-11508ae19c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mandates/update/26']</value>
      <webElementGuid>10032cb4-12ff-41d3-af24-2e5161729c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
