<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Test company for QA</name>
   <tag></tag>
   <elementGuidId>3c62dac5-9232-49db-a63d-0778ab044da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mandatesGrid-container']/table/tbody/tr[3]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>03f0d3dc-e506-41cd-9a38-4dd7b2068cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>9be42f6a-d5c2-4632-b28a-fc149b0cbf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2722e8c-daaa-42ae-b561-010e5e9cc52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>e5e7f8f1-c32b-4ac3-90f8-3c8a987ddf35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>8e70e06a-3e79-4fe4-899a-dc8bd511ba92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8e2d8296-af54-497a-bbcd-4ddfc563f3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>5f66e604-5aad-443c-bc64-06dc6e3a3b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33040179-e2fe-4894-8a54-970c669330c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>9d3f1961-7b2a-40ba-ae5d-7cd56414615b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>3299a610-e66b-4702-9340-c28d6b83ec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0ea94223-bb3b-4711-9654-1ee23a374d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>e2ae9b87-46ec-46a2-aaa3-10795451cc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>34caa5ff-5681-4177-be0c-f03466cd8c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>82f5c6bc-768a-4321-806c-a13c5d6abd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>6de44abb-b38b-45ce-8e7e-d18fc8b4c27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0bbeed39-6312-4c19-bd03-0fb378ca463d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>d44e77be-30c4-4089-a57f-3b9f08ebaa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10351b33-2113-48dc-9eda-a345104c9e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>13218dde-1e25-4fbf-8d74-8ab9eebcf6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>13bbe66d-2b7e-4f1e-b134-f9a71578b844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>60b5c8e4-411f-4cce-99cc-e85df3545dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>08189735-2c0b-46c7-8db8-283619346f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ab1d8cf-641f-4483-9981-99d8887253a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>cb9bac7e-7180-4cb9-8d9d-5e6f13151e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>dd7ec301-5bbd-4b15-8759-08e407a39b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f302bc29-56c8-480a-9bff-803b491dea8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>25b94319-f275-46cc-90d8-2ed57c6bb740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2372759f-5cc1-4434-a68d-777c13338e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>fda05d67-0155-42cb-b97b-acaacdc90e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>75a2d6aa-278c-4af7-979c-8c26622f45b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b29d485f-8c94-49c5-9986-4b5bf45c1865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>4b70cb81-5649-4073-8d11-9a43382c6841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47019e93-0b97-421c-a57e-e568acfd5fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>d41cead1-397f-4485-b77f-ac5ecb8f3f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>87f7a71f-8c0d-47e5-b591-a9e95edc9b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>84555bd1-53bd-4342-947f-d929ede34dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>3c3124e2-0886-4039-828d-b1225d0d9911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4661cfaa-ac33-4235-951f-80ca44761327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>92ae0497-8a63-4674-85f3-7cfea977befc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>c5327739-2cab-40ef-b44e-e0f673c21132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b3833212-8fe4-4244-bdb3-aa5a0673d6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>3eeaf418-b300-40ac-a4a0-167ee68a0ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1885f4e9-1e08-4a36-ad44-15e388cbfb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>68c41f1c-5b22-4f71-81d3-8206937ca72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>58debfdc-0faf-4c62-ab44-fe85a7c1e6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d989ed23-7743-47fd-96d5-a5396ddb498c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>11c275bf-2a78-4379-8837-6902c021e840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c8ef57c-4be9-403e-ba0b-f862f30e915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>3d3d32c8-eac7-4603-80fa-5c6290115024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>3607b12f-2128-406a-8777-0fac9bea61b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>04d8119c-6070-431f-8d10-fce0a494eca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatesGrid</value>
      <webElementGuid>e756dc2a-443b-4e12-8d64-2717877d5701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-seq</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f02b4088-e637-4cfa-aa39-ca3f341cf474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test company for QA</value>
      <webElementGuid>38d44739-33f7-4c8d-b003-edf638b48ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandatesGrid-container&quot;)/table[@class=&quot;table table-hover table-grey text-center vertical-center table-responsive kv-grid-table table-bordered table-striped kv-table-wrap&quot;]/tbody[1]/tr[@class=&quot;mandatesGrid&quot;]/td[@class=&quot;mandatesGrid&quot;]</value>
      <webElementGuid>5e751e8a-39fc-44c7-9603-5b4cd8fc16b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mandatesGrid-container']/table/tbody/tr[3]/td</value>
      <webElementGuid>4abbbbf5-990b-4ab2-8b80-71a1cb778ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquired'])[2]/following::td[2]</value>
      <webElementGuid>ca384e3f-88b0-4aab-89c6-9fedcb513e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ivan Godonuk'])[2]/following::td[3]</value>
      <webElementGuid>3f4ef983-9a0b-45c6-b3e7-c0728d2b1fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Engineer (m/w/d)'])[2]/preceding::td[1]</value>
      <webElementGuid>124695c8-01a6-45a3-b40b-d263bd789cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>8c338a6a-1d93-4751-bb19-44a8e940591f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Test company for QA' or . = 'Test company for QA')]</value>
      <webElementGuid>cdcfe9fd-a1fb-4c4e-94bb-ad6c556e772f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
