<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Wade Weber</name>
   <tag></tag>
   <elementGuidId>ff93e369-11f0-4a31-a8a1-70dfa6c91e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='candidateBlock0Display']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ee5f8146-0d8d-4be2-b38d-00fd348e8e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>5a9d91f9-29d1-4ff5-a8d7-a77895606330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>be32dd61-9a04-47f4-9b11-a26225ad5156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>3ef1f744-ba8c-4fd2-89ea-29b443576609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4aaa362c-fd97-4160-9c30-e83a9ffb90a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>aca8c38a-9317-41fb-9379-c90242e682cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>8a2d8679-9581-462a-8aa0-626b1775308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>1c2aae81-5242-4f9e-b2eb-f9cc96cef2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3eb4a389-e1fb-4045-9ef1-f084fb5ac5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>e5f7e0c1-46be-48b1-b10a-a14957113f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>376d63bd-51d2-4c29-b9e8-2fbd62835ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>d9110b19-217f-4479-9d92-c041c3dee6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>366fa500-0933-438c-8d0c-f90f389131fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>09b96472-82d5-4462-b0f9-59d0cb25d61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>ddb9e3f5-33e2-41e7-b12c-199060fb90da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>9de85f51-bc03-442b-a617-6a44f9500564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fa752687-5b4d-4fa0-b838-98a9e7be8412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>d7db6e02-087c-41c1-88b4-fa53880fd715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>26ffaad4-3dc2-496d-a30b-15e20b3f45b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>df3497fe-200e-4092-bb09-ce8282a4ba80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>10b6fbda-826d-4cdd-b7ab-3072061d4c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>a443ce44-8eca-45b3-b27a-54330933d8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Wade Weber                                    </value>
      <webElementGuid>efb703ff-5cd5-4e60-9b84-04110b392674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>406b6b46-94ea-43c6-905c-4c1cfa56d033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='candidateBlock0Display']/div/div/div/h1</value>
      <webElementGuid>1219bb9a-2070-4c99-8a1d-b60cc4bb354e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      <webElementGuid>9b31329e-2887-42d3-b01a-660a776504ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::h1[1]</value>
      <webElementGuid>d1c19fb1-b328-4844-9371-43f0bb9c454a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::h1[1]</value>
      <webElementGuid>e9172f7a-ecf0-4d46-bd17-9cd4d5cfc349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>373325e6-ff72-4a91-b3a2-1fec7a93cd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Wade Weber                                    ' or . = '
                    Wade Weber                                    ')]</value>
      <webElementGuid>668136df-236e-4734-ad9a-f68827f4cb04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
