<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANCEL</name>
   <tag></tag>
   <elementGuidId>13096c5d-276c-4bb7-8a91-9dd09f0e7f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='candidates-form']/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43dc6795-e5bf-4cd6-8305-dd035dd374e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>d29e3ce0-26b7-428d-9146-383b25c9f236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>bff872ab-6a9a-467e-87a1-930548c13505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>f04ec189-01c9-4681-8ab7-86b69afbf3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>96c204f5-4b18-4b0c-8e22-7e57493f741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64d90df1-498e-461a-8430-7887d77f6b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>12a98bdd-be44-4bcf-b654-91059a81a2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75</value>
      <webElementGuid>00062e7f-f41e-43d1-b07d-4660087acbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>ceb69fbb-0c4a-4acb-85ba-a923efc2d4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>f4dfbae7-1a6c-442f-9d5d-9748136b9679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10c30939-75d4-49bc-ab81-90d1bf88e1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>d3c3aa64-3cdb-4684-b925-60d95abd4329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75</value>
      <webElementGuid>5da9551e-f13f-4ff7-9975-a94f7c1cff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>d13d11d9-5ab7-4082-a1dc-bf61db4b0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>4b1a4312-9ad4-4728-982b-588f318dd8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='candidates-form']/div[2]/div/div/a</value>
      <webElementGuid>d9307bd2-248a-4263-b958-6767b6a7d4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANCEL')]</value>
      <webElementGuid>3da1e06c-0498-4a7d-889b-9445be3388bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPEICHERN'])[1]/following::a[1]</value>
      <webElementGuid>c712c0a9-3501-487b-a94d-ae75ef90776f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail'])[1]/following::a[1]</value>
      <webElementGuid>93608e71-f9ec-4e0c-a6e3-a34104220804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[1]/preceding::a[2]</value>
      <webElementGuid>dd30b6e2-1fc6-40a6-bd1b-67abc9767065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCEL']/parent::*</value>
      <webElementGuid>58182aea-deb3-4944-b608-38277505813a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rocken-sandbox.cheitgroup.com/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5')]</value>
      <webElementGuid>ff710952-499c-408d-85cb-7b910a83f14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>a52b98c3-04db-4a4e-a240-87eb8200880d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rocken-sandbox.cheitgroup.com/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>2a1e4fdc-3503-47b9-af20-e5698ca6cdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75')]</value>
      <webElementGuid>1c7011f8-72f0-4258-9b65-c0296bb1fd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>8b5d43b1-72f9-4ba3-9d45-b4d5723126b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
