<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANCEL</name>
   <tag></tag>
   <elementGuidId>13096c5d-276c-4bb7-8a91-9dd09f0e7f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='candidates-form']/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64d90df1-498e-461a-8430-7887d77f6b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>12a98bdd-be44-4bcf-b654-91059a81a2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75</value>
      <webElementGuid>00062e7f-f41e-43d1-b07d-4660087acbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>ceb69fbb-0c4a-4acb-85ba-a923efc2d4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>f4dfbae7-1a6c-442f-9d5d-9748136b9679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10c30939-75d4-49bc-ab81-90d1bf88e1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>d3c3aa64-3cdb-4684-b925-60d95abd4329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75</value>
      <webElementGuid>5da9551e-f13f-4ff7-9975-a94f7c1cff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>d13d11d9-5ab7-4082-a1dc-bf61db4b0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidates-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>4b1a4312-9ad4-4728-982b-588f318dd8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='candidates-form']/div[2]/div/div/a</value>
      <webElementGuid>6ca29887-904e-4b8c-93b0-6b0cd7a3990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANCEL')]</value>
      <webElementGuid>0c185f52-dcbb-4d6f-a15e-58239e1a5700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPEICHERN'])[1]/following::a[1]</value>
      <webElementGuid>c5ae059f-3303-43db-acc5-864c72fd2a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail'])[1]/following::a[1]</value>
      <webElementGuid>0afeae38-29cb-402d-8e32-0b165dbae39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[1]/preceding::a[2]</value>
      <webElementGuid>1cacd6a0-cba4-4e90-9360-bedde5aeabf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCEL']/parent::*</value>
      <webElementGuid>6e323881-b7be-4d45-8736-0621ce550936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75')]</value>
      <webElementGuid>1c7011f8-72f0-4258-9b65-c0296bb1fd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>fab9f5f5-e8f0-42b8-b07d-8e2adcb1e840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rocken-sandbox.cheitgroup.com/applicants?CandidatesSearch%5Bconsultants%5D%5B%5D=75' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>8b5d43b1-72f9-4ba3-9d45-b4d5723126b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
