<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Junior QA Engineer (mwd)</name>
   <tag></tag>
   <elementGuidId>f9c950e6-7dc8-4aa1-ab1f-2dc66b554ea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.vacancy-banner__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Johnson Controls GWS GmbH'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7b2280e2-cfec-4884-af5a-31b032ed6a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vacancy-banner__title</value>
      <webElementGuid>9d37d4c3-84f4-406c-8bd4-13b069c8276e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Junior QA Engineer (m/w/d)</value>
      <webElementGuid>01c9bd0b-17a2-4cf2-9a9d-8aa2d7672999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;publications-template-default single single-publications postid-7036 cookies-set cookies-accepted&quot;]/section[@class=&quot;vacancy-item&quot;]/div[3]/div[@class=&quot;vacancy&quot;]/div[@class=&quot;vacancy-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/h1[@class=&quot;vacancy-banner__title&quot;]</value>
      <webElementGuid>962ead16-7820-4205-8135-c09ffc1920a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c83b66d5-9d27-4dd2-803d-a884358dce05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vacancy-banner__title</value>
      <webElementGuid>9c6ebde2-0bd2-4bb5-8c8f-db38e8f42d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Junior QA Engineer (m/w/d)</value>
      <webElementGuid>4c811b44-cd5e-4a79-b057-83b54719b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;publications-template-default single single-publications postid-7036 cookies-set cookies-accepted&quot;]/section[@class=&quot;vacancy-item&quot;]/div[3]/div[@class=&quot;vacancy&quot;]/div[@class=&quot;vacancy-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/h1[@class=&quot;vacancy-banner__title&quot;]</value>
      <webElementGuid>e982f747-fa29-40a1-9fef-387d6021a999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Johnson Controls GWS GmbH'])[1]/following::h1[1]</value>
      <webElementGuid>91a3fe30-e2e5-4a8d-a223-f7012aa3660b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junior QA Engineer (m/w/d)'])[1]/following::h1[1]</value>
      <webElementGuid>e08473bb-545c-431a-b325-2130892c7262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID: 3731'])[1]/preceding::h1[1]</value>
      <webElementGuid>5d4a3bc6-6d69-4d99-89d2-ed037757b5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anfahrt'])[1]/preceding::h1[1]</value>
      <webElementGuid>8f94520b-1614-43f0-ab9d-e8a8c538eaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>27c2466c-4e13-42ef-ae9d-c94e79b291c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Junior QA Engineer (m/w/d)' or . = 'Junior QA Engineer (m/w/d)')]</value>
      <webElementGuid>000a429a-b006-4ada-8f7a-5bc9537d823c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
