<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profiles</name>
   <tag></tag>
   <elementGuidId>2e85cead-09c2-4518-a242-a9531a240e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.candidate.treeview > ul.treeview-menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ROCKEN® Talents'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e57d2bb7-bde2-4d22-b7ee-1c8fabc07087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>8de2f4bf-f90b-46ce-b960-f3631d2fb206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f51d199-2100-4c86-8073-e9407afc7d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Profiles </value>
      <webElementGuid>adc0b2bd-afd5-42be-8738-e75180f521b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;candidate treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>6540b46a-7d69-4dc2-b50d-7b661b925559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71b784a5-f9e6-4aa9-b4ae-7df2b09c1b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>15595cbe-edf9-475b-a02f-6d528ec41a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12c3eaba-e037-446e-a74f-724fa705351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Profiles </value>
      <webElementGuid>bbdaefb5-dc5c-4b75-ba6d-e5878e7c1108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;candidate treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>64a3716e-6d71-4f99-8bee-2600412a465a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a948d74-e662-41c8-abd8-8ca15678cb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>55e0b4cf-77d2-4504-a1e8-ed37161877d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e4dd9dd-90d5-4bdc-b7a6-2bd2f88c2410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Profiles </value>
      <webElementGuid>6ed19d03-8f38-4d34-a8f2-e91f38648d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;candidate treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>b881ef0c-fce7-4bc6-856f-08793072eff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6705bd2d-3de9-4b3f-bff7-8755d7431bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>76ca663c-9a24-4693-acef-f01af127e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9efb5387-5e7f-4b82-9184-ad9ad901bad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Profiles </value>
      <webElementGuid>9bf4aa05-c98a-47f1-a14d-564dd0977e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;candidate treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>2f00919a-1458-4e38-9abc-f5f5ae5643cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49e25fab-86eb-479e-b826-72c3b0c5c50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5</value>
      <webElementGuid>fec335bc-c28a-4d7a-b81b-26adccf246b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>500a6432-cff6-4c31-a3a5-e5d4a16b482e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Profiles </value>
      <webElementGuid>41a97cf6-2973-4cb5-8e3e-18e47d9dee4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;candidate treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>d25bc627-742d-42ab-a625-a9cbbc2e9eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROCKEN® Talents'])[1]/following::a[1]</value>
      <webElementGuid>9b6e5e40-a92e-4308-8598-801b8077e963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejections'])[1]/following::a[2]</value>
      <webElementGuid>84edb9c8-ecaa-494c-9726-f2d332e73c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[1]/preceding::a[1]</value>
      <webElementGuid>59c74cd8-a9db-4daf-b052-93d93141f516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5')]</value>
      <webElementGuid>54e654fd-eb97-4778-8b2d-709a5b63814d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>7a2440cf-f205-42d5-8989-70ee856e0628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/candidates/index?CandidatesSearch%5Bcandidate_status%5D%5B%5D=5' and (text() = '  Profiles ' or . = '  Profiles ')]</value>
      <webElementGuid>b5d731cd-90a3-41aa-a7ca-86e6864bfdf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
