<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Publications_fa fa-circle-o applicant_applied</name>
   <tag></tag>
   <elementGuidId>e3c8a983-6b39-481e-8330-39ddb3e8050d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-circle-o.applicant_applied</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/ul/li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>36b90eb9-7082-440b-ba2f-bf66de621151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o applicant_applied</value>
      <webElementGuid>af5be190-82ac-4e53-93e2-afe4a48ed173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse sidebar_show&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;application activeclass treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[2]/a[1]/i[@class=&quot;fa fa-circle-o applicant_applied&quot;]</value>
      <webElementGuid>722ae3ab-9e7c-46d8-8f83-ce98748e6ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>980d78ec-24eb-43ee-b39c-6fdd2296a61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o applicant_applied</value>
      <webElementGuid>20242b50-3a60-4903-898b-82b7d7998b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse sidebar_show&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;application activeclass treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[2]/a[1]/i[@class=&quot;fa fa-circle-o applicant_applied&quot;]</value>
      <webElementGuid>9e916fb3-a327-4765-947b-b895ba768ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c021aaa5-1c2a-43e9-8f5c-72d94ca4c191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o applicant_applied</value>
      <webElementGuid>ee4c50c3-1ad8-42cd-b27f-26db109f540e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse sidebar_show&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;application activeclass treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[2]/a[1]/i[@class=&quot;fa fa-circle-o applicant_applied&quot;]</value>
      <webElementGuid>8aca80d2-bf0e-4bb1-b5ba-5b4b1067a873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a/i</value>
      <webElementGuid>df24ad9c-7b84-453b-8c2a-c13299b3b64f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
