<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil anzeigen</name>
   <tag></tag>
   <elementGuidId>553a71d9-4769-420d-9a34-b0b4e7da83db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.uppercase.btn-flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='candidateBlock0Display']/div/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e0b917d-e8c3-42e9-9f0a-cf594911f039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e</value>
      <webElementGuid>e90dbc65-6997-4b04-a0db-82f4520e0e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase btn-flex</value>
      <webElementGuid>257bdf8d-763b-4162-aa20-e842417d4367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9075d977-631d-4878-864b-dcff4fcb779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Profil anzeigen                </value>
      <webElementGuid>915fb8d2-3a2c-4c62-ab05-fd474372060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head-btn section-head-btn-d-block d-flex pull-right&quot;]/a[@class=&quot;btn btn-warning uppercase btn-flex&quot;]</value>
      <webElementGuid>894b946c-a361-4e60-85c6-2297a56a1926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69c4f924-3939-411b-b0c2-faaf5088911f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e</value>
      <webElementGuid>03c3c12f-d3a2-45ab-8fe8-cabf518d2e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase btn-flex</value>
      <webElementGuid>07490f79-1857-4e32-a9cb-f00350c5968e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>77da404e-0cfc-4707-8fd2-14fde0741fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Profil anzeigen                </value>
      <webElementGuid>34fc4cbd-fd5c-4c39-a824-b46d381eef6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head-btn section-head-btn-d-block d-flex pull-right&quot;]/a[@class=&quot;btn btn-warning uppercase btn-flex&quot;]</value>
      <webElementGuid>01b2c2b0-9252-4752-b033-b472a268c474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56534a8f-20d2-4eec-a257-582088d4582c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e</value>
      <webElementGuid>f637cb97-ce70-4c31-b9bb-dc3a82007d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase btn-flex</value>
      <webElementGuid>6db9f816-563e-4c09-881b-d6217fa37c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bc5236ae-bbdd-42c5-adfe-2edf3e5fb0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Profil anzeigen                </value>
      <webElementGuid>3b8b2c03-0c57-4560-ab9c-018b6c247418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head-btn section-head-btn-d-block d-flex pull-right&quot;]/a[@class=&quot;btn btn-warning uppercase btn-flex&quot;]</value>
      <webElementGuid>8473b0e6-9d2f-4039-92c9-4e5a01c44ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>147c7665-c11f-42a8-8a31-242b209ff827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e</value>
      <webElementGuid>c173bb5b-cec7-434b-b87c-27dc704413e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase btn-flex</value>
      <webElementGuid>7aa47dd5-27a4-4724-8f9a-e278d25dfe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a06e392f-ab4f-4c75-a254-13f89264f2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Profil anzeigen                </value>
      <webElementGuid>d82b8e2e-b6d1-426d-87d4-2d89396acdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;row d-flex align-center mb-3 candidates-view&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;section-head-btn section-head-btn-d-block d-flex pull-right&quot;]/a[@class=&quot;btn btn-warning uppercase btn-flex&quot;]</value>
      <webElementGuid>7901da0f-5ba1-4204-9cd3-bcda1a29334e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='candidateBlock0Display']/div/div[2]/div/a[2]</value>
      <webElementGuid>af2070e0-2a34-434f-8937-ca9dc5b03643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Profil anzeigen')]</value>
      <webElementGuid>d1838916-ae00-4f39-90d3-c8315c9c0238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANFRAGE SENDEN'])[1]/following::a[1]</value>
      <webElementGuid>824070e2-1752-44b6-b530-cfd64d6805c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active sourced'])[1]/following::a[2]</value>
      <webElementGuid>1bb8b68a-74ff-4692-a9cd-694aa68d6c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktionen'])[1]/preceding::a[1]</value>
      <webElementGuid>68fcd034-03be-48d9-bd20-aa79d04a073a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Executive Search exportieren'])[1]/preceding::a[1]</value>
      <webElementGuid>ac3d284a-c53b-4a83-a801-13220216fb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profil anzeigen']/parent::*</value>
      <webElementGuid>335b93b9-ea0c-40c9-bb62-5ffb1f6fc616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e')]</value>
      <webElementGuid>5f6db580-de59-49f3-b02f-31c6e3975816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>fe77fc67-4d02-4951-963a-14a5d86b1350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rocken-sandbox.cheitgroup.com/profile/wadeweber_ye8e' and (text() = '
                    Profil anzeigen                ' or . = '
                    Profil anzeigen                ')]</value>
      <webElementGuid>16365207-20cf-416b-b333-2a42a9f51a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
