<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Wade</name>
   <tag></tag>
   <elementGuidId>d4c05886-5db6-4194-a2a3-9e747789bf16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0c2d3849-4b5c-4f47-9ed9-e61c36612d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>a8a77686-f9f7-43b9-9033-5189244e42b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wade</value>
      <webElementGuid>7aa6bd23-2a1a-4f8c-998e-f957f1cc58e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>383cad58-6c78-4464-ba95-3f98bd37b47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>12dfb8c0-d222-45b4-b881-9aae030b997d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>e3b8a506-12e8-4316-8d87-3ca8607f4f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wade</value>
      <webElementGuid>1fd3b309-ec62-49cf-81c9-1ca147827c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>624ad0e3-d7d4-4f0b-8a9c-98700e8d360a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b1be9476-b2c8-40f7-8f18-cfdbeee907ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>eafb5ac3-86f5-47d4-b1b6-a049b2468927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wade</value>
      <webElementGuid>70600c86-c4ca-49cc-af56-6cb3840a75dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>2ac5de2e-4f07-4369-a894-89d64ba06af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0ec51860-d86c-4ab9-a6fd-3eb73d322985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>b100ec98-94ad-4ace-8f59-d8d9128416f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wade</value>
      <webElementGuid>2c84201f-a03d-445d-8785-279be701daf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>169f8a3b-4f98-4965-a38f-ba45c7256d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>93cdc2a4-a5b1-4519-8579-ce082df50971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>c679e3cf-7152-456e-b311-9da3f4c8e463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wade</value>
      <webElementGuid>0a03862c-1bf3-47e8-bec7-6c54f34ee316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>fc3bd5d1-a988-40b6-a249-299f8fcf783f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>1837dd5c-7c21-48ea-be35-c3a0703c2c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vorname'])[1]/following::td[1]</value>
      <webElementGuid>38d65a43-ab60-415f-b8ef-4896360800d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Herr'])[1]/following::td[2]</value>
      <webElementGuid>db2b3814-4e21-4158-b139-81e3f2591eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nachname'])[1]/preceding::td[1]</value>
      <webElementGuid>ca514806-7fca-43dc-8e53-3ef00156a5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weber'])[1]/preceding::td[2]</value>
      <webElementGuid>98b21983-bfb0-4820-90d0-e7cf0159e18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wade']/parent::*</value>
      <webElementGuid>8b5f3153-9348-4dda-881a-003be0040172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>4a8f8ffc-df34-44f1-a557-99b5dce0c3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Wade' or . = 'Wade')]</value>
      <webElementGuid>2ce915a8-38f4-4583-948f-ac122ed717eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
