<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Weber</name>
   <tag></tag>
   <elementGuidId>f757b8ca-b309-4192-9866-9a70419d0273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e2aea39f-6317-4b53-b130-970d6d5b6cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>41f0664b-5379-4d4b-b65b-22060db10e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weber</value>
      <webElementGuid>4ba8fb2f-8d24-4760-9623-b87656df9ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>7d9f076e-91cb-476e-8e8f-0c77b6e092ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bd70d1f0-bbc9-49ee-8230-06ecca2e821d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>69fcd22e-bc79-40fd-8ea6-fd5ded9edf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weber</value>
      <webElementGuid>7e11fc5f-64a6-4d90-a258-03429f1fa93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>6abd2eff-4e83-40d7-b1d9-18f914ca3a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>de9a258b-fc61-44cb-b85b-ad5e8c8cca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>519bf087-67c2-42e8-94a1-74981003baf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weber</value>
      <webElementGuid>fdf7f12f-dde3-4568-9ea4-57b76eec465e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>d87b576f-b191-4232-bf6d-f3e8282785d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>81388603-2a0c-4cd6-99f0-6c19ef2fb5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>988c27bc-e253-4a97-8574-098430424645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weber</value>
      <webElementGuid>751962c5-4646-4141-bbd7-2c75f2d8ddbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>56642cf0-02cd-467d-b14c-a78425214d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a55d0171-c72b-4fb6-8bd1-207f15e8de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>c7cd39d1-559d-45db-8a95-705322dc3c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weber</value>
      <webElementGuid>cd59cd42-945e-4409-ba45-da5ec4b505d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>29c2a5f5-2a2e-401f-a3c5-5bf15629dd63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>6157ded4-ef0b-4e26-9328-d414886aa614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nachname'])[1]/following::td[1]</value>
      <webElementGuid>0acb685c-6d7b-4ec5-83f1-7b046cb13bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wade'])[1]/following::td[2]</value>
      <webElementGuid>759adde6-81f9-4527-8445-8431ea2dd372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geburtstag'])[1]/preceding::td[1]</value>
      <webElementGuid>81c304e0-102c-49e0-b7f9-faac57be06eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Familienstand'])[2]/preceding::td[3]</value>
      <webElementGuid>857c028d-bfed-4d24-851a-984cae77d25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Weber']/parent::*</value>
      <webElementGuid>bfd02d95-e727-48ea-bdb0-40d1e04785c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>e8b4ed1e-b4c7-4547-9809-374c72ad0874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Weber' or . = 'Weber')]</value>
      <webElementGuid>54fcd1ed-ca03-4a43-9702-99367f8c1985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
