<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Neue hinzufgen</name>
   <tag></tag>
   <elementGuidId>35614835-12f7-427b-a74e-a90436edc364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='filterForm']/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2557b8f9-056d-4a59-aeb8-323fb0621868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>c3326272-8b15-4e74-b9e8-9f9d31bff241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>84d2bfa9-e9c7-40ab-bf2d-925ddf0ac007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>baba98ee-f6cf-4a89-b9a8-b4a6d2d31da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>381b2395-f569-429e-8764-a59a10ba967e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4393f61-95ff-4600-9406-2fdd9a50015b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>8ecc8471-5117-471e-8ff2-48370145a1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>7c677ff3-a82e-4e14-93ee-42fa7e3d7ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>6f173382-ce7b-4238-8931-ea81c8f25d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>7b274985-33c6-4959-bfae-dff6e7f0094e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4299c05b-73e9-4aaa-97a1-1bb3d0a5b9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>06bc0edc-0580-41ac-b526-64bad2bea3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>dda6262e-54be-488e-bedf-2a84ca2ce43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>9356a872-42a2-4259-9dac-3716bd4089b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>a70ec483-9e1b-4c2c-b98e-f5659437927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e33067d5-79dd-4cde-b413-d1793d9b3f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>d715dcfb-640a-4cfc-bd6d-d2acc5536253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>7aab0853-bd08-4100-922e-93f03480fbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>9792cb2d-5a17-41f0-ac5a-8c5c1ee75fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>b8050918-74d0-4a5a-84df-6955fd5e4f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b094d02a-5fa8-4dc3-b272-246cab3798f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>a9b01e2c-5411-4b91-96ca-9d6c679014c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>5e835250-de6c-4aa1-96fc-7b9001a395d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>ec717b53-8a60-4f9e-8bf0-de1d1dddf452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>72a16f75-d7f7-4062-9479-8076507b98d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90b17129-3f0a-4cca-9285-258d19528328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>7fe4a7d6-4e2a-4271-9ae0-5029b0a8b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>0a2a91aa-b25d-4968-9b9c-455d0dd21c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>a1f0d391-5f51-432d-9b0e-3fa024add49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>8ef40ba1-45ef-447b-b8fe-da146e7f7553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>475c31ac-27a1-43df-a6e9-24c5ccad6ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>370f0ca6-1062-436a-b5e6-6829bd7af30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/executive-staff/create</value>
      <webElementGuid>f8a28adf-2f67-432e-8237-dccfb813dac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>7e039a3e-8857-42e4-9b51-11488ad13bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>36031c8c-5492-48ec-bca1-d0cbf3721862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filterForm']/div/div/div[4]/a</value>
      <webElementGuid>e53545f0-94f1-4d08-87d7-6f63e8153875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Neue hinzufügen')]</value>
      <webElementGuid>d36f7a03-d34e-4fff-96b8-0e7ff914dcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::a[1]</value>
      <webElementGuid>f6e45e7d-4569-42ba-8818-d6c9f2166c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hint: Push “Enter” for searching by keywords'])[1]/following::a[2]</value>
      <webElementGuid>0f83d0a4-f118-485e-a24b-6b8141287c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::a[1]</value>
      <webElementGuid>4b677d5c-a62a-44ee-a17e-619aa7402044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neue hinzufügen']/parent::*</value>
      <webElementGuid>72651767-d4f6-4a96-9a5d-60f433e894e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/executive-staff/create')]</value>
      <webElementGuid>2e16fe6b-699c-4532-8c73-ea2a2274187b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>5d134d88-41b5-4a41-8147-e553019415f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/executive-staff/create' and (text() = 'Neue hinzufügen ' or . = 'Neue hinzufügen ')]</value>
      <webElementGuid>e2033d58-45a4-4a16-81b2-3315bbbf19c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
