<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Neue hinzufgen</name>
   <tag></tag>
   <elementGuidId>e37fe06f-3284-4edf-8510-e3d5dd173a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='filterForm']/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>077033fe-a3de-4d01-b1ed-588b92ea804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>257b8d45-1b71-40e8-b063-89e6478da094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/create</value>
      <webElementGuid>733ace92-afa2-4f3b-bf00-dcd18f4ada50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>f930fe0c-7be3-4fd9-bedf-0be7a3705ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>98f9dce5-72da-4a60-88bd-ed334e77404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63115c96-7e5e-45b2-ab30-bea4edbeb1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase</value>
      <webElementGuid>dac852cf-e01f-411d-9d14-e89479e1a8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidates/create</value>
      <webElementGuid>76bde794-3f28-4f08-a334-03cc29a7f170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neue hinzufügen </value>
      <webElementGuid>9b661ea0-b224-48d7-ba39-fae9d8a6ef8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterForm&quot;)/div[@class=&quot;page-head-section&quot;]/div[@class=&quot;row d-flex align-center row-sm&quot;]/div[@class=&quot;col-xl-auto&quot;]/a[@class=&quot;btn btn-primary uppercase&quot;]</value>
      <webElementGuid>8dd7e23a-c80a-437a-ae6f-8a3f65f4d8aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filterForm']/div/div/div[4]/a</value>
      <webElementGuid>cf14861b-f9cc-44a6-8633-60211648d79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Neue hinzufügen')]</value>
      <webElementGuid>42539535-04c3-4228-b0de-616cabd6f285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::a[1]</value>
      <webElementGuid>3ecde06e-2d92-49ad-b027-331d37392c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hint: Push “Enter” for searching by keywords'])[1]/following::a[2]</value>
      <webElementGuid>766d6908-c675-4e1c-9cd0-6910eb016c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filters'])[1]/preceding::a[1]</value>
      <webElementGuid>b52fe235-632b-4642-9066-9d55c3bdcc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATEGORIE'])[1]/preceding::a[2]</value>
      <webElementGuid>0552d9b5-3992-43f5-ae31-2d8f44202351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neue hinzufügen']/parent::*</value>
      <webElementGuid>06d312b5-47e4-4bc4-9710-ebcfe28a783d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/candidates/create')]</value>
      <webElementGuid>2dfc4cd4-18ca-4d11-a01a-5d713109074c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>3c470fb2-86d3-47eb-b6d1-1035774cdfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/candidates/create' and (text() = 'Neue hinzufügen ' or . = 'Neue hinzufügen ')]</value>
      <webElementGuid>4f13946f-b4fe-40e2-b8fd-c715793d03b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
