<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview Vacancy</name>
   <tag></tag>
   <elementGuidId>6f22f61b-be5b-4bb3-88ae-524ecd88df8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Preview Vacancy')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8fa95a4a-a183-4488-846e-2d473b582684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase</value>
      <webElementGuid>6feb223d-b49d-4cbd-b1fc-2b1a6d151845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vacancy/vacancy-from-geneva-mwd3794</value>
      <webElementGuid>83b41112-31be-4913-b2df-c62c3bf56133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f290cfbb-fa54-44e4-92ae-822c61f925b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview Vacancy</value>
      <webElementGuid>56ed31e4-8a39-4089-8436-d491f8b9a0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6 section-head-btn three-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-warning uppercase&quot;]</value>
      <webElementGuid>436badb2-7e11-420d-877c-e0cf756b43d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a81411e5-3c34-4dab-88f1-ed41a38816d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase</value>
      <webElementGuid>b0f78656-d8c6-43f0-8fe9-961eadc8efd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vacancy/vacancy-from-geneva-mwd3794</value>
      <webElementGuid>b3f9fd34-4f65-4995-8730-c9980d2f62c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>15b18785-4021-474d-adb2-2554e81a3ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview Vacancy</value>
      <webElementGuid>f0f0f13d-1c0c-46a9-8487-3936f69148dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6 section-head-btn three-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-warning uppercase&quot;]</value>
      <webElementGuid>05385e5e-ad85-4468-9978-02b16fcf7ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f24a292-eed8-4151-8126-3e715116101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase</value>
      <webElementGuid>e2becb00-0579-4fdf-930b-0a88522f9c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vacancy/vacancy-from-geneva-mwd3794</value>
      <webElementGuid>07cb68c1-19b2-4ae8-8cb0-dc3e46ba42d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e736e841-136a-4f12-a0a9-da44c2534eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview Vacancy</value>
      <webElementGuid>a4aad4a5-a037-4c57-97ed-137cadceb22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6 section-head-btn three-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-warning uppercase&quot;]</value>
      <webElementGuid>b67d7831-336b-48a8-853e-0efa99ed20b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>194270f7-77c3-4a66-b473-d23c6fa21d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning uppercase</value>
      <webElementGuid>165bec53-068a-4e2d-9ce7-5e88e3deca7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vacancy/vacancy-from-geneva-mwd3794</value>
      <webElementGuid>0edfd735-e9fd-4343-9161-0d9f1e736355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f666d9ce-77ac-4a56-a82e-4277ee95f6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview Vacancy</value>
      <webElementGuid>138df0c8-f9c0-4620-be43-c8750f910146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6 section-head-btn three-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-warning uppercase&quot;]</value>
      <webElementGuid>768f283f-d1cc-47e8-a409-6643acc66fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Preview Vacancy')]</value>
      <webElementGuid>d40bdc71-dfc1-4c59-84aa-37e1b20aee65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/following::a[2]</value>
      <webElementGuid>703b7f2a-af34-4ef5-9437-55c3720d407a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process type'])[1]/following::a[3]</value>
      <webElementGuid>b1315def-8e4b-4024-8a4f-d9d38b6b4809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Vacancy'])[1]/preceding::a[1]</value>
      <webElementGuid>d3401d5a-6d8a-4cae-bfd3-6461ef4433f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::a[2]</value>
      <webElementGuid>3757a53a-96e0-4a25-bad8-293a76e5641f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview Vacancy']/parent::*</value>
      <webElementGuid>1f639c10-bc5b-4c03-bf30-5457a47ffed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/vacancy/vacancy-from-geneva-mwd3794')]</value>
      <webElementGuid>1d7e9567-a74b-4995-a137-f27ea77e1eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>7232270f-dd4d-414b-a1fc-2c3b46ae9936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/vacancy/vacancy-from-geneva-mwd3794' and (text() = 'Preview Vacancy' or . = 'Preview Vacancy')]</value>
      <webElementGuid>bd3e7646-03db-498e-a149-9d720bdbbbd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
