<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Vacancy from Geneva (mwd) (V3794)</name>
   <tag></tag>
   <elementGuidId>4c802ed0-ef08-471b-a1c2-30e61586f4d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f9a43ede-d2be-4b92-a609-77d367790a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>2a91b889-7e17-496a-a586-b74ca4807a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Vacancy from Geneva (m/w/d) (V3794)                </value>
      <webElementGuid>8b96ad0c-7a58-4bd4-8667-664224d90dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>ee32e21b-48bf-4695-9c55-7f1f19a6efb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6bb22725-e5b4-41cc-94fb-7299d38f2848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>94386eed-13fd-43fe-8f49-afd8ec37b994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Vacancy from Geneva (m/w/d) (V3794)                </value>
      <webElementGuid>0a455149-f037-44a7-94df-1195a4bd504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>3aab77f0-448e-4c68-b57e-7b57dd9faf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>34c9a0d7-b0b0-48ab-b735-d197d248cdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>afa3ead8-085d-48a2-8a92-20ea6c5f1479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Vacancy from Geneva (m/w/d) (V3794)                </value>
      <webElementGuid>995aa6a5-9e05-4931-a2a9-67ceea473568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>3911ebf9-4955-4e31-82f9-78ddfc0c5277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9cb4033e-3983-4fe3-8ee4-cfcc1e7e341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>c851f0ae-969d-4a00-88b8-5d332195ebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Vacancy from Geneva (m/w/d) (V3794)                </value>
      <webElementGuid>2e311e0d-bb07-46a5-9849-e680600ef9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>6185c543-ae54-4063-a869-2f9702e38ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8dd8e60e-0353-4ccb-b7bc-9aa31a8ed1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>1c08844c-553d-4af2-a19d-2f99b156f9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Vacancy from Geneva (m/w/d) (V3794)                </value>
      <webElementGuid>b5b648fd-c1e7-4937-b939-ceea609f63ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;vacancies-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-lg-6&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>b30cef70-764c-47ce-a56f-fd21a34c0466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      <webElementGuid>5c865815-fa2b-498b-b977-a5cbf422950e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positionen'])[2]/following::h1[1]</value>
      <webElementGuid>684ace44-1af2-448b-8721-bdd78cb7a05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::h1[1]</value>
      <webElementGuid>019f70d0-521e-49dd-a98f-2fa2cfe3e358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vacancy from Geneva (m/w/d)']/parent::*</value>
      <webElementGuid>697270fc-b25c-453a-b15e-51f37c6a88cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>9ef0857c-d7ad-4c5a-8f01-4cbfe7383d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Vacancy from Geneva (m/w/d) (V3794)                ' or . = '
                    Vacancy from Geneva (m/w/d) (V3794)                ')]</value>
      <webElementGuid>126dfeb2-9a2f-4420-a68e-0432b55452d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
