<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Global Tracking Settings</name>
   <tag></tag>
   <elementGuidId>a14ecbbc-b583-4f1d-a38a-15199a79e2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0130f8a0-56c0-4874-820b-ddeca9502eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company-tracking-settings/index</value>
      <webElementGuid>3d465316-1a02-4810-b514-602ae24ba7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6069a5d8-26ef-406c-be8c-f4b79b580107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Global Tracking Settings</value>
      <webElementGuid>2a0417dc-4803-47c4-8149-717753ea1116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;company treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>13bf2f78-8299-4ae5-b6ba-8e326c00436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eef92f72-bf9a-431e-973d-95f014344b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company-tracking-settings/index</value>
      <webElementGuid>cb2f9298-7480-4e12-bb66-2495863e4355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48aa2878-f327-4ac9-bca9-3337c39206ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Global Tracking Settings</value>
      <webElementGuid>97910293-0f90-4de7-99d3-166cac47963d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;company treeview&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>a13aec71-79ab-47ea-a5d7-449cebf9cc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies'])[1]/following::a[1]</value>
      <webElementGuid>8eb4b2c9-ca6f-40a6-990e-f79296115bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executive Staff'])[1]/following::a[2]</value>
      <webElementGuid>9ec4f51b-fe37-4d5e-96e7-7d6f9826ae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application-Management'])[1]/preceding::a[1]</value>
      <webElementGuid>d3c55e1c-fb02-4127-b10f-77e9b7713208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/company-tracking-settings/index')]</value>
      <webElementGuid>4b7b1b62-fc0a-4059-8858-914421b20967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>673a35fc-9815-42fb-8c72-8b7d23729cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/company-tracking-settings/index' and (text() = '  Global Tracking Settings' or . = '  Global Tracking Settings')]</value>
      <webElementGuid>7322cd5f-c833-40e0-8502-f93fa79375db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
