<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to ROCKEN.jobs</name>
   <tag></tag>
   <elementGuidId>e3e436ee-2d0a-4b17-9f34-d0dbce6f8785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-purple</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Go to ROCKEN.jobs')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be643fd6-d8a4-4e09-a3e2-70fe753ec815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-purple</value>
      <webElementGuid>3202d194-6271-41dd-b412-7da96336a680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rockenjobs.dev.cheitgroup.com/?p=7036</value>
      <webElementGuid>7d16d50d-dd51-4a60-8084-4f8de6ec5640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6530ae83-5c3c-4cee-8a19-978bcdfbb55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to ROCKEN.jobs</value>
      <webElementGuid>e130c420-eb91-4e3a-b097-5f0a47d23e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;publications-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-sm-6 section-head-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-purple&quot;]</value>
      <webElementGuid>805ba2a2-2e07-477c-9991-deb45985cd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37ce1ea4-fcec-4bc9-b8cd-53f3a02e8227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-purple</value>
      <webElementGuid>2e589b2c-f8c1-4c99-ae0a-4073e48b1cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rockenjobs.dev.cheitgroup.com/?p=7036</value>
      <webElementGuid>f6cd20a0-f80d-4040-8332-b620213fc254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0d16ba4f-6d26-4578-9e5d-df08f250b384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to ROCKEN.jobs</value>
      <webElementGuid>45d7ba2b-6178-4299-97b4-715a4097d812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper section_bottom_fixed&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;publications-view&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex align-center mb-3&quot;]/div[@class=&quot;col-sm-6 section-head-btn section-head-btn-d-block&quot;]/a[@class=&quot;btn btn-purple&quot;]</value>
      <webElementGuid>69fc22bf-8c55-4046-95b8-ee6dfcfa7036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go to ROCKEN.jobs')]</value>
      <webElementGuid>f00b91f7-03ac-4968-b584-a90a1d91dab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Published'])[1]/following::a[1]</value>
      <webElementGuid>16511960-b850-47f1-9ff9-de2e68377fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>70c2b2fe-3dc5-412b-a113-ec8e34ae7794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT'])[1]/preceding::a[1]</value>
      <webElementGuid>275fb019-9cd2-4bae-97b5-64be82de7ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::a[2]</value>
      <webElementGuid>e02270c5-4ae0-4d7e-a63b-55de39fdc873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to ROCKEN.jobs']/parent::*</value>
      <webElementGuid>46a34de0-ec8f-442a-b7f7-69dd339d7360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rockenjobs.dev.cheitgroup.com/?p=7036')]</value>
      <webElementGuid>72a50e32-bd65-4064-bb65-e20a437c3090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/a</value>
      <webElementGuid>263e12fc-87e9-40b5-b285-4a77a475fcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rockenjobs.dev.cheitgroup.com/?p=7036' and (text() = 'Go to ROCKEN.jobs' or . = 'Go to ROCKEN.jobs')]</value>
      <webElementGuid>fa72e551-fcb9-4d2b-9d3e-975bc3130c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
