<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANCEL</name>
   <tag></tag>
   <elementGuidId>731c9637-93cf-4732-94d1-2b680e33c18a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.btn-save.btn-mw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='publicationsForm']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47025bef-a736-4386-808d-3aa650f496c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-save btn-mw</value>
      <webElementGuid>a32083ab-d0a2-4fe4-9191-7efd9a7ad84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/publications/create?autosaveClear=1</value>
      <webElementGuid>edce56da-3635-4dfc-b1f2-19ce992f13a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>0ee5cb7f-97a8-4d89-ad85-a5a3d55ff7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicationsForm&quot;)/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-default btn-save btn-mw&quot;]</value>
      <webElementGuid>5faa3e24-b635-42c0-9c75-7dcf2ba5c160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52bdbcca-07e0-42c6-881e-0ccc2af7d3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-save btn-mw</value>
      <webElementGuid>3385c491-e91f-43bb-8d9f-7636f24face1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/publications/create?autosaveClear=1</value>
      <webElementGuid>aac325db-0862-4da9-ac60-74a3e9bed14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>54dd74de-9d3a-4dfc-b08b-9942f5dd3f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicationsForm&quot;)/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-default btn-save btn-mw&quot;]</value>
      <webElementGuid>b7fee7f9-8709-488c-8c61-4b4bae63706b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2834ad3a-05e9-4560-8117-b9c5ebc4fbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-save btn-mw</value>
      <webElementGuid>7ba0adfc-ad86-4039-99b6-63c649a8be99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/publications/create?autosaveClear=1</value>
      <webElementGuid>af6d8f10-931a-49a7-a782-8a9b394cefb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>be25649e-8b64-40b7-a337-a4f493372fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicationsForm&quot;)/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-default btn-save btn-mw&quot;]</value>
      <webElementGuid>ac0b6051-a610-4d5e-9e32-410c40569c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c9efc06-7c60-4eed-99df-43523cf62d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-save btn-mw</value>
      <webElementGuid>9f5e60e8-a43e-41b1-8999-a8ee1c3a5ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/publications/create?autosaveClear=1</value>
      <webElementGuid>ad14216c-2677-454a-8671-a696cbd5daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>5151a828-e75f-4075-9cf2-4fe2628892bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicationsForm&quot;)/div[@class=&quot;section-head-btn&quot;]/a[@class=&quot;btn btn-default btn-save btn-mw&quot;]</value>
      <webElementGuid>f0f263d5-cfe4-4bb9-8b44-35bd0c4bb9bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='publicationsForm']/div/a</value>
      <webElementGuid>8e45f964-ccac-415c-bfbd-f97f5e8b2858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANCEL')]</value>
      <webElementGuid>15c9522e-9084-467d-b0ba-24d31663d95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE AS DRAFT'])[1]/following::a[1]</value>
      <webElementGuid>f98e99c5-3c45-4763-b1f8-7db7bd8e60a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLISH NOW'])[1]/following::a[1]</value>
      <webElementGuid>6123d352-ebea-4216-9c9e-523ab49aa456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hauptinfo / Main info'])[1]/preceding::a[1]</value>
      <webElementGuid>4a1bf059-3d1b-4b29-96a3-b73190aca2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status *'])[1]/preceding::a[1]</value>
      <webElementGuid>29008f39-fa67-4916-b853-ab81cfc2230b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCEL']/parent::*</value>
      <webElementGuid>2cf5c362-ba64-499c-ac56-543b3371c63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/publications/create?autosaveClear=1')]</value>
      <webElementGuid>aceaa05e-be3d-4fef-bb04-c27b0a633b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>f851f6a2-5666-47e3-8add-aa4ad49f8a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/publications/create?autosaveClear=1' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>e7373c06-094f-484c-ba55-028376d8fd29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
