<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Applicants 6</name>
   <tag></tag>
   <elementGuidId>8645d166-2856-4cce-bee0-a407cf67737f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='NotificationsTopicsList']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ddfc546e-0dd8-41ad-9605-823054764681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=applicants</value>
      <webElementGuid>8304b79b-3f1d-4900-9d18-71012d1fc8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=applicants</value>
      <webElementGuid>c7874e50-5510-4522-a7fa-e87e2a52c086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab_id</name>
      <type>Main</type>
      <value>applicants</value>
      <webElementGuid>390216e2-9ea8-4c4c-ac50-91afb72a8ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06d0d1fb-a6ee-4451-8882-d1cf3064fcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99c247e7-a0c8-425a-94a6-e880fcdb22e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Applicants 6                            </value>
      <webElementGuid>8af348cf-9bd5-4321-b8cd-ce3f81bab7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationsTopicsList&quot;)/li[@class=&quot;topic-tab&quot;]/a[1]</value>
      <webElementGuid>e86a4fc3-aa09-45ca-8cab-0b2275b5d94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='NotificationsTopicsList']/li[2]/a</value>
      <webElementGuid>46ff4957-9a73-4088-89fd-c03a44c508d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies and Publications'])[1]/following::a[1]</value>
      <webElementGuid>522b29ad-ad9e-45f3-9ca9-8dd445619ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktionen'])[1]/following::a[2]</value>
      <webElementGuid>be4ab05c-9296-4201-8628-1b0bc4f5b1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[3]/preceding::a[2]</value>
      <webElementGuid>89f7dc25-7be3-4552-a595-fb401a836a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notifications?NotificationsSearch[topic]=applicants')]</value>
      <webElementGuid>860ca69f-39a7-41e0-b3f8-246b84b7f1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>755e4dc3-9141-4771-b94c-ab5b39c86305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/notifications?NotificationsSearch[topic]=applicants' and (text() = '
                                Applicants 6                            ' or . = '
                                Applicants 6                            ')]</value>
      <webElementGuid>2370f321-f2d2-47bd-9be7-b08b796ea431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
