<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Companies</name>
   <tag></tag>
   <elementGuidId>a0755c16-9b1c-4a54-95f3-149ea222a0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='NotificationsTopicsList']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee5a4a68-c500-49db-8036-1937df07baaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=companies</value>
      <webElementGuid>29f41d1e-8daa-45ce-945e-8afa736f89fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=companies</value>
      <webElementGuid>73fa57ac-0409-4b72-8602-e199b3b6ff5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab_id</name>
      <type>Main</type>
      <value>companies</value>
      <webElementGuid>0bc12208-99bc-4256-a285-1de31e2b05ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba3f04bc-70ec-43c3-a5ae-a48c1e84b366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fdb12e9-3f33-4197-9d3f-82b67a8ecfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Companies                            </value>
      <webElementGuid>c4aeee7a-cd3f-47ca-b4d4-64ee9d828a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationsTopicsList&quot;)/li[@class=&quot;topic-tab&quot;]/a[1]</value>
      <webElementGuid>978345fa-1059-4b51-9b1d-9c735cdb264f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='NotificationsTopicsList']/li[5]/a</value>
      <webElementGuid>ebd36cb8-364c-49c8-ab99-a6f9bd1a254f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Companies')]</value>
      <webElementGuid>9a6b0f59-8fad-447b-a6ba-64f34dced16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[3]/following::a[1]</value>
      <webElementGuid>510e7e75-94d4-4ed8-9fca-cc69226dcf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark all'])[1]/preceding::a[1]</value>
      <webElementGuid>7c02d183-0c31-4a52-afee-cf0b9b66e8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start new process !'])[1]/preceding::a[1]</value>
      <webElementGuid>f3763a7e-b7cf-4d77-a90a-a803d3bd752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notifications?NotificationsSearch[topic]=companies')]</value>
      <webElementGuid>dad31dd7-444a-43c6-b72d-a789159010a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]/a</value>
      <webElementGuid>86dfa437-dc4a-48eb-af26-b756b7c4451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/notifications?NotificationsSearch[topic]=companies' and (text() = '
                                Companies                            ' or . = '
                                Companies                            ')]</value>
      <webElementGuid>29536ef8-aba1-4898-b0cb-d43400e61fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
