<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profiles 1</name>
   <tag></tag>
   <elementGuidId>a935a8a5-2327-4ea4-b7c3-ffce062527cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='NotificationsTopicsList']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1955b069-8b2e-4149-a52c-aef9f1e3f41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=candidates</value>
      <webElementGuid>1971d2e8-4803-4edb-9ca4-0f48960bc50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=candidates</value>
      <webElementGuid>bba71aeb-bef7-4638-acdb-e79de7b948cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab_id</name>
      <type>Main</type>
      <value>candidates</value>
      <webElementGuid>bf31a5e4-1e99-4900-abbc-62b7cc0cdf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5c5bc2a-60c3-4081-a06b-70da808bb035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ccefe2b-def5-45b2-bb37-58f948e34ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Profiles 1                            </value>
      <webElementGuid>cc1694c8-b6d9-43ed-b54a-3d2eb6b31645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationsTopicsList&quot;)/li[@class=&quot;topic-tab&quot;]/a[1]</value>
      <webElementGuid>f46bf818-438f-4c9c-a6ab-43742d2ac60f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='NotificationsTopicsList']/li[3]/a</value>
      <webElementGuid>ef086f84-d7e3-460a-b63a-be87581d388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies and Publications'])[1]/following::a[2]</value>
      <webElementGuid>0bf82798-5c18-4b41-b69d-e2b38dd58239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[3]/preceding::a[1]</value>
      <webElementGuid>bc6985cd-8870-49a9-9b7e-c1f92aae4c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[3]/preceding::a[2]</value>
      <webElementGuid>2b642161-3703-43f9-bd50-14119b430a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notifications?NotificationsSearch[topic]=candidates')]</value>
      <webElementGuid>6fab2df3-33e0-4df7-bf43-5f7432bbcf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>c87e9147-3b52-45a0-86f1-6a5f6c5b1e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/notifications?NotificationsSearch[topic]=candidates' and (text() = '
                                Profiles 1                            ' or . = '
                                Profiles 1                            ')]</value>
      <webElementGuid>5043bb6e-e65d-4450-80e2-3545444b08df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
