<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Processes</name>
   <tag></tag>
   <elementGuidId>a880aada-5131-47cd-8ed8-1944cb2e7d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='NotificationsTopicsList']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29b6f658-e0d3-4a7e-b2a9-4df4ed56103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=professional_search</value>
      <webElementGuid>e027b2f9-7e48-492b-84e9-37bafe2644ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=professional_search</value>
      <webElementGuid>738b6752-a5b5-424c-ad1b-42dcdaa8facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab_id</name>
      <type>Main</type>
      <value>professional_search</value>
      <webElementGuid>47aac17d-e8e0-45ae-b21e-57c1d720dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98e84950-c7ab-4c0f-ba1e-fe002165419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33383375-5983-4b32-83a3-39a93c1dd91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Processes                            </value>
      <webElementGuid>5437f360-07b4-4555-a6a3-66618a17364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationsTopicsList&quot;)/li[@class=&quot;topic-tab&quot;]/a[1]</value>
      <webElementGuid>1d768e93-ad8c-40a4-ae44-c47d17f4c817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='NotificationsTopicsList']/li[4]/a</value>
      <webElementGuid>e77ea355-7512-409f-b877-5d1fdf19efac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Processes')]</value>
      <webElementGuid>c019c63a-e670-4833-8b5c-fb314ee7e29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[3]/preceding::a[1]</value>
      <webElementGuid>6ca096f5-4a39-401c-91d7-19eba4472907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark all'])[1]/preceding::a[2]</value>
      <webElementGuid>0d0783ba-e95d-4d2d-b00c-affb2c7ee277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notifications?NotificationsSearch[topic]=professional_search')]</value>
      <webElementGuid>4dc8afe1-1a03-48dd-a18e-dfe85dd3f96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>d8adc377-3bfa-4bc1-a931-cc78ad3b27a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/notifications?NotificationsSearch[topic]=professional_search' and (text() = '
                                Processes                            ' or . = '
                                Processes                            ')]</value>
      <webElementGuid>25f305ee-f3fd-4765-b185-956f2e9f80b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
