<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vacancies and Publications</name>
   <tag></tag>
   <elementGuidId>9414650e-3974-47dc-abb0-4b9db4dbb936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='NotificationsTopicsList']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90b4c404-f1a0-4197-a8cc-6c2075a48b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=vacanсies_and_publications</value>
      <webElementGuid>0d5f9dfb-82a8-419f-af69-36b5d4d0d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/notifications?NotificationsSearch[topic]=vacanсies_and_publications</value>
      <webElementGuid>c2610af0-28d4-44c7-bca1-e3fa4e36dcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab_id</name>
      <type>Main</type>
      <value>vacanсies_and_publications</value>
      <webElementGuid>1ad9b8bd-526f-45bc-af44-780a14ceccb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a0fa534-5d81-450c-beb8-8544d651b5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2b66d5a-a9fe-4394-9ab2-defb7ed63854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Vacancies and Publications                            </value>
      <webElementGuid>e6b8b802-f859-4755-8b33-5e8420590f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NotificationsTopicsList&quot;)/li[@class=&quot;topic-tab&quot;]/a[1]</value>
      <webElementGuid>3276ee72-c225-4de9-89c4-b09dc87b0109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='NotificationsTopicsList']/li/a</value>
      <webElementGuid>e09ec1f4-4983-4d70-bb40-602490b92958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vacancies and Publications')]</value>
      <webElementGuid>4a52bcce-af3f-448b-95f0-70f9285b1f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktionen'])[1]/following::a[1]</value>
      <webElementGuid>9da02ab8-2172-415c-b587-378e9bc7021e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[4]/following::a[3]</value>
      <webElementGuid>7c9ad8d5-0de8-487e-b61c-525234d0d62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vacancies and Publications']/parent::*</value>
      <webElementGuid>2ec3309c-e326-4fc0-9959-56e506a445df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notifications?NotificationsSearch[topic]=vacanсies_and_publications')]</value>
      <webElementGuid>9a983856-62a2-46ff-b730-8c562151d158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>b3aaa5f1-4a03-4a36-a7cf-49a4330c4cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/notifications?NotificationsSearch[topic]=vacanсies_and_publications' and (text() = '
                                Vacancies and Publications                            ' or . = '
                                Vacancies and Publications                            ')]</value>
      <webElementGuid>93039ad3-c86c-47f0-be7d-7189d67552ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
