<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Add to Mandate</name>
   <tag></tag>
   <elementGuidId>38db2855-80af-4a96-8167-36bf728a307b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h5[@id='exampleModalLabel'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-11 > #exampleModalLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>0444c850-cf36-4ee4-9c74-4908d969b51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>611d568c-dc1d-43d8-b4f0-d0d774d76faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>5b9af761-d0d2-40ab-b14f-dc10641aeba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Mandate</value>
      <webElementGuid>9b25c424-33c9-4bd4-b8f8-3c40631dfe44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-11&quot;]/h5[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>2154a69a-e7ce-45c5-aac1-67453f720aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>cd8ea487-c5fe-402f-9b83-b3b1a67ddb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>14ba2f3e-7301-402b-8f56-f06189eb3f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>79e6268c-c2ff-4c11-8466-445bb4ba42cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Mandate</value>
      <webElementGuid>9bd82d3b-400a-402f-baf0-b5131afbc86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-11&quot;]/h5[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>c2b43d55-a134-4fc2-ab00-9be4a5f571db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>819140e9-1e96-4e2b-82ae-1f2c91744b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>9196780b-89c4-4ec5-bc60-427573f74c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>7f3d7fb4-b747-4c73-9988-6090b04efea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Mandate</value>
      <webElementGuid>0ca19c6a-2c36-476c-ba23-676b20bbc1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-11&quot;]/h5[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>4bcf08ea-d0cd-4c16-8a37-88f51ad1fa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>3ace15e0-1656-44be-b0e6-e74f22e7e0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>4e735c75-5cec-4e5b-b643-459fa55a7638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>15e05414-7aa4-45ac-b81b-791fe02348bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Mandate</value>
      <webElementGuid>9afc003f-a8db-478b-b40c-7041fefdc59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-11&quot;]/h5[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>587d1d2e-576d-4282-aeed-60496ee56fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>10e45b8a-3253-4dec-8ef0-cd753d90f8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>bf9eb78c-8fb7-4ad5-825f-6d4b66bc2756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>779a93ad-1277-4602-8232-a60f7ba8dcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Mandate</value>
      <webElementGuid>435c8073-7f9d-43c9-bf2b-50ded7376853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-11&quot;]/h5[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>07ea3222-61bd-4366-a7b5-eda094acd679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//h5[@id='exampleModalLabel'])[3]</value>
      <webElementGuid>35a98756-d35a-4db3-8841-1d037e890e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mandateCompanyModal']/div/div/div/div/div/h5</value>
      <webElementGuid>cc3908cf-5d1c-4bce-b58e-c4b443d17008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Mandate'])[2]/following::h5[1]</value>
      <webElementGuid>57ceca63-d4a7-4dcf-901f-f7798b48bdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Mandate'])[1]/following::h5[2]</value>
      <webElementGuid>390b6dec-7595-4c73-838d-549ed9f3f753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[4]/preceding::h5[1]</value>
      <webElementGuid>577a11d8-dc1a-402d-a3da-09e39f3b8edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abbrechen'])[1]/preceding::h5[1]</value>
      <webElementGuid>95331386-e758-43fc-8d56-a6670cefbc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/h5</value>
      <webElementGuid>3c9afacf-63bf-4c5e-8d75-23e4d5930476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'exampleModalLabel' and (text() = 'Add to Mandate' or . = 'Add to Mandate')]</value>
      <webElementGuid>3af7fef5-307f-4410-9647-a0b2befb9100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
