<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Cruz</name>
   <tag></tag>
   <elementGuidId>bb1f04eb-5883-4b79-8db7-1ac0c93dc2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e58335f8-3ee1-4aae-86b0-ae0fc8e1f837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>07d56c6e-046b-491b-a360-4d341b4e5dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cruz</value>
      <webElementGuid>6babbf95-9577-41cf-a278-e1191baed57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[3]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>9f4c88c3-1154-4243-b9d5-81ac2fab5cf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>d37ec0b0-0e3b-4b2d-9f49-de3a9864d8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nachname'])[1]/following::td[1]</value>
      <webElementGuid>83b84e56-b66f-4b7d-b067-1e4e4bd1fab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nero'])[1]/following::td[2]</value>
      <webElementGuid>cc16cbbf-3a68-467a-b3a6-6ce2856730f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geburtstag'])[1]/preceding::td[1]</value>
      <webElementGuid>d7207faf-7f72-4d7a-8910-45e8c2350674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[2]</value>
      <webElementGuid>891731ce-099c-45cb-8c6d-366396f8a331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cruz']/parent::*</value>
      <webElementGuid>580877f7-daee-48e7-80a8-b1e44136c052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[2]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>59ce8a98-e3c8-405b-aebb-a5bd451f2352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Cruz' or . = 'Cruz')]</value>
      <webElementGuid>8094c547-fcb3-4dd2-9386-2a560810c233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
