<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nero</name>
   <tag></tag>
   <elementGuidId>769caa70-7701-43a3-8ca7-22daf72981b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>36af9d2b-bf31-4afd-8066-9e495cf69f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-label</value>
      <webElementGuid>c3ae9e5a-764a-4f5f-8f2c-84e129ba87de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nero</value>
      <webElementGuid>62978f2c-1709-40d7-b6b7-9d61e03594b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;table_body&quot;]/table[@class=&quot;table table-no-border&quot;]/tbody[1]/tr[2]/td[@class=&quot;table-label&quot;]</value>
      <webElementGuid>7fe774aa-c325-4c81-89ac-63d17ff4efef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_1']/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>19ae2265-388b-4c71-aa40-d37cf5179e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vorname'])[1]/following::td[1]</value>
      <webElementGuid>2681f707-b408-4ba3-8518-97276a7ed4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Herr'])[1]/following::td[2]</value>
      <webElementGuid>73fd1831-5621-4da4-a572-de0ca49421ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nachname'])[1]/preceding::td[1]</value>
      <webElementGuid>2f6604d5-14bc-4256-a634-ceb2e8eb62f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cruz'])[1]/preceding::td[2]</value>
      <webElementGuid>d02bdfb0-1188-4d15-b206-0a00279f7a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nero']/parent::*</value>
      <webElementGuid>c9254159-f622-44fa-bc58-09403946bae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[2]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>3d9f0d0f-2bd6-4530-b7b2-5b96658a7849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nero' or . = 'Nero')]</value>
      <webElementGuid>7ed1ff74-dad0-47b4-ba96-8ac67a285756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
