<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Hedley Meadows</name>
   <tag></tag>
   <elementGuidId>4929aef9-8e53-4460-9d14-13ddb9f220c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='StaffHeader']/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ac7facb3-a18e-4079-9918-fc7a6b5cea8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>0c3d1509-937a-4d0b-9d38-261006e5f319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hedley Meadows                </value>
      <webElementGuid>fd1fdcbd-d4eb-482d-987c-dae15460a58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffHeader&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>376fd5b2-5997-4bd5-8de8-9e4b4a5a04db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>108c156b-7334-4abe-93dc-cebe15f77f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>f066b735-6c0d-462c-85fe-1cfa224d7a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hedley Meadows                </value>
      <webElementGuid>4558536a-23ba-4bec-aaff-4ed47f96a0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffHeader&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>a1e6a495-0bd7-4c94-b1f0-1130a54c7f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2599effd-f68b-4aa5-a503-4add3d4cb31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>6b2d841b-a443-4e03-9738-dc854cb5872a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hedley Meadows                </value>
      <webElementGuid>1fd00eb3-6418-4cfc-9456-a13457d581f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffHeader&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>dab4fcf9-d09f-4f9e-a3c1-4c02fae48b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>480108d6-8c1d-4cef-b430-e7672a7ff69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>83bcb458-e094-4cc1-95fe-675eccd81730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hedley Meadows                </value>
      <webElementGuid>d9869418-c03d-4a1c-b092-f15ecff36c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffHeader&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>e02f4e20-e43f-4893-beb0-ed81917e81a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6d04297e-1f22-4a51-acc1-113ec07044bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>cf2a8210-31b5-42d1-86b8-358451dfc6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Hedley Meadows                </value>
      <webElementGuid>ea0bb1fa-fbdb-480d-9af8-74fa863e36f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StaffHeader&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>be88db97-5667-4d11-8ed5-52ed8c1ea488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StaffHeader']/div/h1</value>
      <webElementGuid>2ee9f41e-e975-4c51-9be6-07b088f8189b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      <webElementGuid>8600ec56-f19f-4fc7-b463-7f4b534f9436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::h1[1]</value>
      <webElementGuid>e7b20011-9a3f-43a6-a020-00bc46875da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incomplete'])[1]/preceding::h1[1]</value>
      <webElementGuid>64caf027-18bd-44cd-8cc5-4bc70022a6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>09239283-bfff-4270-b1f4-f0033ccfa224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Hedley Meadows                ' or . = '
                    Hedley Meadows                ')]</value>
      <webElementGuid>94ecf4cb-09da-41e2-a570-967d19a6dc08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
