<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Bewerbungen</name>
   <tag></tag>
   <elementGuidId>4398cf7d-5c90-4a06-ab10-a089b3c07e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.h1_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='applicationsGrid']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5c0dc364-bc62-4b37-8385-515b7d77aff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1_title</value>
      <webElementGuid>4ac4a1c5-80eb-4a59-8455-737b8d0d3ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bewerbungen</value>
      <webElementGuid>f5af1d25-2bf9-407c-bf38-5dca5f9c2c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicationsGrid&quot;)/div[@class=&quot;applications-index index&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/h1[@class=&quot;h1_title&quot;]</value>
      <webElementGuid>5c71cb86-e5db-4c6f-87a2-79e62ae5522c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='applicationsGrid']/div/div/div/h1</value>
      <webElementGuid>62fe59b2-af41-4232-afe5-ef9bc8ebb9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      <webElementGuid>6c1eaa77-fe65-4441-bf87-6793bc4a5f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positionen'])[2]/following::h1[1]</value>
      <webElementGuid>dfa7c905-d125-476f-9ea6-9e356395b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spalten auswählen'])[1]/preceding::h1[1]</value>
      <webElementGuid>b537c1e6-5325-4dde-81cf-df3532ce8ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::h1[1]</value>
      <webElementGuid>f50143ca-8f81-4e97-8f5e-c1a55c904a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>eb7dbb4e-940f-4e7b-9be0-3db9d3933743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Bewerbungen' or . = 'Bewerbungen')]</value>
      <webElementGuid>8a18775d-d82e-4e33-a22e-a00f52848a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
