<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ivan Godonuk</name>
   <tag></tag>
   <elementGuidId>c9259e1c-c96e-4d2d-bd3c-62dc6654593c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='candidateBlock0Display']/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.page-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7d398e9f-fda6-4fe1-8877-556d16b4dd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>cf82337d-2320-4d2c-9d69-09c2c0cb1ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>9dbbf704-9ced-4228-8957-655130439a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>d893f8e5-ec4c-48e1-98d0-f14b2169c31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>13fe3853-3e74-4f14-9f6c-366336dbfd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>f0cb1ca2-ca9a-4584-a622-9728b0615ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>f09c2dbd-1a6c-434b-bbff-3bd4432ad02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>16ae282a-b42c-45f6-8dd8-3713522fec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c93a7246-07b6-4775-9801-c769117f5a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>949285f1-3703-46b5-bff7-a7688ae22cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>5b9b8277-f40a-4919-ab19-40402104b71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>919bb96e-388e-4290-8168-01b66132d011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>787d99dd-73b5-4e08-84d2-87486ec8140b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>025d83ad-b4c2-4192-9174-13977acdb803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>bb4368c8-e12f-4f18-b59e-51e89ebc7097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>5f547b2b-921b-4514-a3de-92993b3e2c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>691a4dcc-1f9e-4a36-b232-83a136fa2d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>e57df5d3-c01c-4df0-a192-029fab06a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>de5cc257-ad87-43e5-a3d3-032ce1cc03a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>379c6a6c-c389-40c4-a510-d4a515fe10bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6da74a19-81cb-464e-8e3e-52885dde5620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>760393ff-5b99-4899-b0fb-dd78364759a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>56be2c6d-d155-429b-96bb-c756ebc157a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>663d9e76-7a3a-4116-ba33-23791986d933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>109283b7-635a-4e12-a410-5f4c83b421c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>d8605f63-741e-4127-b209-22a95b385ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Ivan Godonuk                    </value>
      <webElementGuid>614f45f1-cc07-498f-99ae-9246712bea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateBlock0Display&quot;)/div[@class=&quot;section-head&quot;]/h1[@class=&quot;page-title&quot;]</value>
      <webElementGuid>84cf56e7-90ef-43f5-9f4b-73ecd9644a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='candidateBlock0Display']/div/h1</value>
      <webElementGuid>21696e73-e87e-43ea-ac18-771707e3c787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantone'])[2]/following::h1[1]</value>
      <webElementGuid>05d52d6c-e732-4cee-afc7-cedc7997bfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positionen'])[2]/following::h1[1]</value>
      <webElementGuid>a450b9ea-fdbb-4c12-a552-fddacaa54684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::h1[1]</value>
      <webElementGuid>aeb0d6d9-06d3-4a7c-a183-edcb0976ddc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit profile'])[1]/preceding::h1[1]</value>
      <webElementGuid>04828a4d-6456-4cf4-9f72-a0fa3f7c62af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2f78dc1f-9fe1-47fb-aab7-7603ece17214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                        Ivan Godonuk                    ' or . = '
                        Ivan Godonuk                    ')]</value>
      <webElementGuid>286becc1-e553-4df6-8851-1dbaf7902ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
