<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hinzufgen</name>
   <tag></tag>
   <elementGuidId>09704a6d-10d7-4c7c-80ec-3eddc7af31e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mandateCompanyAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mandateCompanyAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d6eaefc-f473-4344-80c4-82dd68a2849d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandateCompanyAdd</value>
      <webElementGuid>e9fa08d9-e718-4285-957c-f840e142378f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase mr-1</value>
      <webElementGuid>ba8e8362-5a97-4883-bc8e-2b9c985eceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4748dde9-a7ca-4957-b1c6-085f4674a90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4d17190e-f0f6-4d90-a77d-f4b703a1c70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mandate</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>d8a4cae8-a255-4526-91b7-7375075c47ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mandateCompanyModal</value>
      <webElementGuid>103bcf83-44bd-4005-9ec5-d7978f04b487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add contact persons</value>
      <webElementGuid>6ecacfdb-fa04-48ab-b1a8-caa3017d7bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hinzufügen </value>
      <webElementGuid>1fa42474-b33e-4d3d-99ff-412b5b8ec2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyAdd&quot;)</value>
      <webElementGuid>52b9f469-9079-4650-88d9-0df41b4f64f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf0ba74f-1e14-4bef-a118-aa7e7d81878b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandateCompanyAdd</value>
      <webElementGuid>3e077aaa-a70d-4823-af38-5386a5ea13e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase mr-1</value>
      <webElementGuid>d80af1ef-116f-40d0-bd21-1da2ae25d6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7dcae74c-d3bd-4012-bc32-406cae53746a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>597008ac-2291-441e-9d3e-152ea0df0ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mandate</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>8e1f3758-7aed-4aa8-b62c-ede6c126115e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mandateCompanyModal</value>
      <webElementGuid>7737f653-e993-4870-879d-4770a1d0cc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add contact persons</value>
      <webElementGuid>6a35e8b1-0de1-4892-bb23-a0eef9e13f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hinzufügen </value>
      <webElementGuid>fc6637f8-ef7d-4c78-85cd-41a01a562026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyAdd&quot;)</value>
      <webElementGuid>0759170e-f589-4037-9d45-055e3707f8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb8f7ab6-716c-4cd6-be71-2ff8a0fc6f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandateCompanyAdd</value>
      <webElementGuid>c9fd52ef-363f-4d1f-a786-02db0ed30243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase mr-1</value>
      <webElementGuid>c8b6e846-43b7-4614-9891-1d606f324025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>743d377c-f511-40f2-a22c-8c378c6dfac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>6a280829-2a0f-4dbb-b741-7417343cd707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mandate</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>1323b1e3-b16f-4c97-8d6f-ed8288fee917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mandateCompanyModal</value>
      <webElementGuid>985979f9-88b5-436a-aba9-b9ae2bd46cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add contact persons</value>
      <webElementGuid>4a9320a5-6d6d-42d1-9518-693dcb90a9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hinzufügen </value>
      <webElementGuid>b4e10a39-f1ad-4d0d-8632-a2ec02927642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyAdd&quot;)</value>
      <webElementGuid>a19d724c-9967-4153-8b50-8ee97d0c05a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7180801-6d17-42a0-9dd5-979400bfe00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mandateCompanyAdd</value>
      <webElementGuid>65ccad62-bc4e-4249-a37e-f76888d05e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary uppercase mr-1</value>
      <webElementGuid>e4415e6a-a71b-4a10-91a9-3e769b501330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cdf4af95-eb45-4c25-b61d-1334b0fa8898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>856eb2f6-d502-4eef-8acd-57467120c94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mandate</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>52ead0e6-de1b-48a1-b438-fa726f090592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mandateCompanyModal</value>
      <webElementGuid>7fbf2ee5-7683-4568-b07d-885385af52ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Add contact persons</value>
      <webElementGuid>14cf7a06-62d3-4827-b432-692b61895de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hinzufügen </value>
      <webElementGuid>b66f6488-1b2c-40b2-8f18-089457379b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateCompanyAdd&quot;)</value>
      <webElementGuid>a516e31a-8f83-4b98-8c09-5ff8a25833d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mandateCompanyAdd']</value>
      <webElementGuid>ce033f94-0df7-4bc7-9dcb-d0c54f41074d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hinzufügen')]</value>
      <webElementGuid>e0309394-4f24-4cb5-8054-b47c7ae6bce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::a[2]</value>
      <webElementGuid>26d0c80e-bd37-452f-96c1-d76f16fe0ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internet, Banken, Industrie, Einkauf'])[1]/following::a[3]</value>
      <webElementGuid>63ac5432-7888-4e52-873f-385ba1660ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zielpersonen'])[1]/preceding::a[1]</value>
      <webElementGuid>b228a8d5-345b-4b17-969c-3d15a7573cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[2]/preceding::a[1]</value>
      <webElementGuid>2cb4681f-2fc2-4e45-81a2-40d008261f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hinzufügen']/parent::*</value>
      <webElementGuid>0e409999-2893-4907-9326-58b1531bcc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>5f604a8b-ff55-4fc6-8bd0-1130e1910410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>a8f10a8c-50cf-4d16-919b-3e9eacb430e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mandateCompanyAdd' and @href = '#' and (text() = 'Hinzufügen ' or . = 'Hinzufügen ')]</value>
      <webElementGuid>a5e3fde5-7155-47af-a9b1-85d77522353c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
