<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Longlist_icon-plus</name>
   <tag></tag>
   <elementGuidId>99643b2b-3f6a-4f38-b156-0144a9f92031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mandateStaffAdd > i.icon-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mandateStaffAdd']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>00ce05d4-c787-4772-8db2-cad4a6d7640a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>49aa49f8-01f5-49c7-b343-434ce7ffa446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>f159c280-f6e6-4bdd-b13e-4365b15558b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>04582a26-efc6-443f-8664-f4889f662586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>e6cb0e3c-d361-4fef-bac4-20c132728cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>d60984f9-2f60-462a-b969-8e8f226bf874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c61406a9-2ee8-4061-8f7d-864cf44a1bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>9e3abeee-4f41-4bd2-b297-4333d7b8d1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>24ed55b8-5543-4132-af74-9968ecd15e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4233c2a-e54e-49d8-9d2a-5cb244751127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>2b1cf896-73f5-497d-8b9f-0af8d9bacf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>51f4c06f-6ecb-4660-bc64-5fd30dfd7cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f1164caf-25bd-4982-a030-e65423489561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>7d035161-084f-49e5-9d06-ced573c87ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>3c455924-c005-49bf-8616-3d6bc2853af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e1b9e5bc-7f12-4c57-a85f-0aaf207f779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>767378f9-b94a-4be8-9621-e548e007686f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mandateStaffAdd&quot;)/i[@class=&quot;icon-plus&quot;]</value>
      <webElementGuid>52993f4b-1f1a-4677-805f-eae953824d7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='mandateStaffAdd']/i</value>
      <webElementGuid>30fba6ab-4954-44e0-86c3-b93671194a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div[2]/a/i</value>
      <webElementGuid>f0f053f1-1693-4a9b-9b60-ad8b41e8a030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
